const requestUrl = {
    //基础档案
    buildList: '/cpmBuilding/list',
    buildListDelete: '/cpmBuilding/delete',
    UnitList: '/cpmBuildingUnit/list',
    UnitListDelete: '/cpmBuildingUnit/delete',
    houseList: '/cpmBuildingUnitEstate/list',
    houseListDelete: '/cpmBuildingUnitEstate/delete',
    parkList: '/cpmParkingSpace/list',
    parkListDelete: '/cpmParkingSpace/delete',
    vehicleList: '/userCar/list',
    vehicleListDelete: '/userCar/delete',
    ownerList: '/userResident/list',
    ownerListDelete: '/userResident/delete',
    // 管家服务
    itemsOutList: '/userArticleOut/list',
    itemsOutListDelete: '/userArticleOut/delete',
    userDecorationList: '/userDecoration/list',
    userDecorationListDelete: '',

    voteList: '/vote/list',
    voteListDelete: '/vote/falseDelete',
    conveniencePhoneList: '/conveniencePhone/list',
    conveniencePhoneListDelete: 'conveniencePhone/delete',
    adviceList: '/advice/list',
    adviceListDelete: '/advice/falseDelete',
    visitorsList: '/visitors/list',
    visitorsListDelete: '/visitors/cancel',
    complaintPraiseList: '/complaintPraise/list',
    complaintPraiseListDelete: '/complaintPraise/falseDelete',
    reportRepairList: '/reportRepair/list',
    reportRepairListDelete: '/dispatch/falseDelete',
    questionnaireList: '/questionnaire/list',
    questionnaireListDelete: '/questionnaire/falseDelete',
    gambitList: '/gambit/list',
    gambitListDelete: '/gambit/delete',
    gambitThemeList: '/gambitTheme/list',
    gambitThemeListDelete: '/gambitTheme/falseDelete',
    dispatchList: '/dispatch/list',
    dispatchListDelete: '/dispatch/falseDelete',
    workOrderTimeLimitList: '/workOrderTimeLimit/list',
    workOrderTimeLimitListDelete: '/workOrderTimeLimit/delete',
    borrowList: '/borrow/list',
    articleList: '/article/list',
    ownersCommitteeList: '/ownersCommittee/list',
    ownersCommitteeListDelete: '/ownersCommittee/delete',
    voiceHousekeeperList: '/voiceHousekeeper/list',

    // /chargesTemplateDetail/list
    chargesTemplateDetailList: '/chargesTemplateDetail/list',
    chargesTemplateDetailListDelete: '/chargesTemplateDetail/list',
    dailyPaymentList: '/dailyPayment/list',
    depositManagementList: '/depositManagement/list',
    workOrderCostList: '/workOrderCost/list',
    expenseBillList: '/expenseBill/list',
    announcementManagementList: '/announcementManagement/list',
    notificationManagementList: '/notificationManagement/list',
    activityManagementList: '/activityManagement/list',
    sponsorManagementList: '/sponsorManagement/list',
    voteList: '/vote/list'
    // List Delete
}
export default requestUrl
